#!/usr/bin/env fish

concat-fasta_bench_AA_openSUSE.sh
concat-fasta_bench_openSUSE.sh
concat-phylip_bench_AA_openSUSE.sh
concat-phylip_bench_openSUSE.sh
convert-fasta_bench_aa_openSUSE.sh
convert-fasta_bench_openSUSE.sh
convert-phylip_bench_aa_openSUSE.sh
convert-phylip_bench_openSUSE.sh
remove-fasta_bench_AA_openSUSE.sh
remove-fasta_bench_openSUSE.sh
remove-phylip_bench_AA_openSUSE.sh
remove-phylip_bench_openSUSE.sh
summary-fasta_bench_AA_openSUSE.sh
summary-fasta_bench_openSUSE.sh
summary-phylip_bench_AA_openSUSE.sh
summary-phylip_bench_openSUSE.sh